---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    dir: functions/update
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - update
      - --memory=256MB
      - --project=${PROJECT_ID}
      - --region=us-east4
      - --runtime=python312
      - --set-env-vars=GCP_PROJECT=${PROJECT_ID}
      - --timeout=30
      - --trigger-event=google.storage.object.finalize
      - --trigger-resource=${_TRUISMS_BUCKET}
      - -q
