---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    dir: functions/slack_redirect
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - slack_redirect
      - --allow-unauthenticated
      - --memory=256MB
      - --project=${PROJECT_ID}
      - --region=us-east4
      - --runtime=python39
      - --set-env-vars=SLACK_CLIENT_ID=${SLACK_CLIENT_ID},SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - --timeout=30
      - --trigger-http
      - -q
    secretEnv:
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/slack-client-id/versions/latest
      env: SLACK_CLIENT_ID
    - versionName: projects/${PROJECT_ID}/secrets/slack-client-secret/versions/latest
      env: SLACK_CLIENT_SECRET